#!/usr/bin/env node
/**
 * Reads secrets from .env.local (local dev) or process.env (CI/CD)
 * and writes src/environments/environment.ts + environment.development.ts.
 *
 * CI usage: set VACATION_API_URL (the Apps Script gateway /exec URL),
 *           GATEWAY_SECRET, and API_NINJAS_KEY as environment variables
 *           (GitHub Actions secrets) before running.
 *
 * NOTE: no Google API key or spreadsheet ID is used anymore — the app reads
 * everything through the gateway, and the sheet is private. See SECURITY.md.
 */
const fs = require('fs');
const path = require('path');

function readEnvLocal() {
  const envPath = path.join(__dirname, '..', '.env.local');
  if (!fs.existsSync(envPath)) return {};
  const vars = {};
  fs.readFileSync(envPath, 'utf-8')
    .split('\n')
    .forEach(line => {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) return;
      const eq = trimmed.indexOf('=');
      if (eq < 0) return;
      const key = trimmed.slice(0, eq).trim();
      const val = trimmed.slice(eq + 1).trim();
      vars[key] = val;
    });
  return vars;
}

const local = readEnvLocal();
const gatewayUrl    = local.GATEWAY_URL     ?? process.env.GATEWAY_URL
                   ?? local.VACATION_API_URL ?? process.env.VACATION_API_URL ?? '';
const gatewaySecret = local.GATEWAY_SECRET  ?? process.env.GATEWAY_SECRET  ?? '';
const apiNinjasKey  = local.API_NINJAS_KEY  ?? process.env.API_NINJAS_KEY  ?? '';

if (!gatewayUrl) {
  console.warn('[setup-env] WARNING: gateway URL is empty — the app cannot read or write data.');
}
if (!gatewaySecret) {
  console.warn('[setup-env] WARNING: GATEWAY_SECRET is empty — gateway requests will be rejected.');
}
if (!apiNinjasKey) {
  console.warn('[setup-env] WARNING: API_NINJAS_KEY is empty — daily quote will not work.');
}

const envDir = path.join(__dirname, '..', 'src', 'environments');
fs.mkdirSync(envDir, { recursive: true });

const tpl = (prod) => `// Auto-generated by scripts/setup-env.js — do not edit manually.
export const environment = {
  production: ${prod},
  gatewayUrl: '${gatewayUrl}',
  gatewaySecret: '${gatewaySecret}',
  apiNinjasKey: '${apiNinjasKey}',
};
`;

fs.writeFileSync(path.join(envDir, 'environment.ts'), tpl(true));
fs.writeFileSync(path.join(envDir, 'environment.development.ts'), tpl(false));
console.log('[setup-env] Environment files written to src/environments/');
